### ISSUE TITLE
Metrics?

### ISSUE THREAD

**Issue by hced** [justinmc/jquery.mobile.fastButtons#1]
Are there any metrics of the speed gains using this, otherwise that would be nice:

jquery.mobile.fastbuttons (vlick) ←vs→ Normal HTML5 click events 
jquery.mobile.fastbuttons (vlick) ←vs→ Native click events

**Comment by justinmc** [comment]
Good idea.  I'm making a note to run some and put the results in the README, I'll get back to you soon...

**Comment by justinmc** [comment]
Alright I've included some nice html pages that allow you to get some live numbers on the kind of speed increases you can expect, as well as actually try the slow/fast versions of page transitions with/without the plugin.  I added some numbers that I got to the README too.

**Comment by hced** [comment]
Those are some sweet metrics! Thanks.
